import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import "@/assets/style/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  weight: ['300','400','500','600'],
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}